### ISSUE TITLE
Mirrorstones don't actually mirror your coordinates lol

### ISSUE THREAD

**Issue by f-raZ0R** [JSJBDEV/Mirrorstones#1]
They seem to only mirror one of them, but make the other coordinate converge towards zero.
Might be an incompatibility with lithium.

**Comment by JSJBDEV** [comment]
You are correct, they don't, but they are not suppose to, they simply take you to the Mirrorstone that is closest to your mirrored coordinates, which sometimes doesn't look very mirrored, but this would likely become more apparent for bigger numbers, I can't see why it would be incompatible with lithium, why do you think that?
